/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javatimer;

public class App {

  public String getGreeting() {
    return "hello world";
  }

  public static void main(String[] args) {
    var game = new Game();
    game.start();
  }
}
